Repository LNSSPsd/PhoenixBuilder, pull requests merged in 2023-01, with the labels that each got.

#159 Rewrite the code for `Legacy Export`
  fastbuilder/bdump/bdump_legacy.go
  fastbuilder/builder/bdump.go
  fastbuilder/commands_generator/setblock.go
  fastbuilder/types/block.go
  io/special_tasks/define.go
  io/special_tasks/export.go
  io/special_tasks/lexport.go
  io/special_tasks/lexport_depends/TranslateNBTInterface/CommandBlock.go
  io/special_tasks/lexport_depends/TranslateNBTInterface/Container.go
  io/special_tasks/lexport_depends/TranslateNBTInterface/NBTInterfaceToString.go
  io/special_tasks/lexport_depends/main.go
Labels: enhancement

#189 恢复 InventoryContent 数据包的解析
  minecraft/protocol/packet/inventory_content.go
Labels: question

#198 为script文档增加繁体中文(中国香港)文档
  doc/script_engine/EN/console.md
  doc/script_engine/EN/consts.md
  doc/script_engine/EN/engine.md
  doc/script_engine/EN/fs.md
  doc/script_engine/EN/game.md
  doc/script_engine/EN/global_functions.md
  doc/script_engine/EN/index.md
  doc/script_engine/EN/module.md
  doc/script_engine/zh_CN/全局函数.md
  doc/script_engine/zh_CN/导航页.md
  doc/script_engine/zh_CN/常量.md
  doc/script_engine/zh_CN/引擎.md
  doc/script_engine/zh_CN/控制台.md
  doc/script_engine/zh_CN/文件系统.md
  doc/script_engine/zh_CN/模块.md
  doc/script_engine/zh_CN/游戏.md
  doc/script_engine/zh_HK/全局函數.md
  doc/script_engine/zh_HK/導航頁.md
  doc/script_engine/zh_HK/常量.md
  doc/script_engine/zh_HK/引擎.md
  doc/script_engine/zh_HK/控制臺.md
  doc/script_engine/zh_HK/文檔系統.md
  doc/script_engine/zh_HK/模塊.md
  doc/script_engine/zh_HK/游戲.md
Labels: documentation, enhancement, localization
